# Generated by Django 4.0.1 on 2022-01-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_bot', '0002_alter_addressbook_email_alter_addressbook_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbook',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='addressbook',
            name='street',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
