# Generated by Django 4.0.1 on 2022-01-31 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_bot', '0003_alter_addressbook_email_alter_addressbook_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbook',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addressbook',
            name='phone',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^\\+?(38)?0(44|67|68|96|97|98|50|66|95|99|63|73|93|89|94)\\d{7}$', 'Enter correct number')]),
        ),
    ]
